### ISSUE TITLE
Remote distribution files from unpkg.com unavailable

### ISSUE THREAD

**Issue by mdeagen** [rdkit/rdkit-js#133]
`https://unpkg.com/@rdkit/rdkit/Code/MinimalLib/dist/RDKit_minimal.js`

redirects to

`https://unpkg.com/@rdkit/rdkit@2022.3.4-1.0.2/Code/MinimalLib/dist/RDKit_minimal.js`

which returns the following HTML error message:

`Cannot find "/Code/MinimalLib/dist/RDKit_minimal.js" in @rdkit/rdkit@2022.3.4-1.0.2`

Additional context:
Unpkg distribution files were available as recently as one day ago.

**Comment by MichelML** [comment]
@mdeagen sorry for this, the distribution files are now at this location since 2022.3.4

`https://unpkg.com/@rdkit/rdkit/dist/RDKit_minimal.js`
`https://unpkg.com/@rdkit/rdkit/dist/RDKit_minimal.wasm`

See readme https://github.com/rdkit/rdkit-js#option-2-use-the-remote-distribution-files-from-unpkgcom

---

It is however a breaking change indeed, I'll release 2022.3.4-1.0.3 with the files at the original location as well for it to be backward compatible

**Comment by MichelML** [comment]
@mdeagen this has been fixed in 2022.3.4-1.0.3

you can either use the old or new path to the dist files now

see https://github.com/rdkit/rdkit-js/commit/a725d0326aaaa945fc3ba50c4aa74a612910728d

closing :+1:
