### ISSUE TITLE
2022_03_2 rdkit-js release build is failing

### ISSUE THREAD

**Issue by MichelML** [rdkit/rdkit-js#347]
@ptosco @greglandrum I'm really busy this week, but the rdkit-js build for the latest release is failing https://dev.azure.com/rdkit-js/rdkit-js/_build/results?buildId=60&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=9c939e41-62c2-5605-5e05-fc3554afc9f5  

The build script is here https://github.com/rdkit/rdkit-js/blob/master/scripts/build_rdkitjs.sh  
The docker image used is here https://github.com/rdkit/rdkit-js/blob/master/Dockerfile  

If you have any idea how to debug this let me know!

**Comment by ptosco** [comment]
@MichelML Hi Michel, that's caused by the updated InChI library - I'll fix that later.

**Comment by ptosco** [comment]
@MichelML This turned out to have nothing to do with RDKit - it is caused by an `emsdk` update bringing along a more recent version of `clang`, which requires some additiional `boost` defines and `clang` compiler flags for he build to succeed.
I also switched to use the `nodejs` version bundled with `emsdk` to run tests as the one coming with Ubuntu is too ancient to support most recent `wasm` features.
I can build MinimalLib with this PR in place - could you please check that it also works in your build pipeline?

**Comment by MichelML** [comment]
thank you @ptosco I will check this today and let you know :+1:

**Comment by MichelML** [comment]
thank you @ptosco , this is resolved and released :+1:
